# Generated by Django 3.2.4 on 2021-06-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='comments_count',
            field=models.PositiveBigIntegerField(null=True, verbose_name='تعداد کامنت ها'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ip_address',
            field=models.GenericIPAddressField(null=True, verbose_name='آدرس آیپی'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='likes_count',
            field=models.PositiveBigIntegerField(null=True, verbose_name='تعداد پسند ها'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='posts_count',
            field=models.PositiveBigIntegerField(null=True, verbose_name='تعداد پست ها'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='', verbose_name='عکس پروفایل'),
        ),
    ]
