# Generated by Django 3.2.4 on 2021-07-07 19:02

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس دسته بندی')),
                ('position', models.PositiveIntegerField(unique=True, verbose_name='مختصات')),
                ('status', models.BooleanField(default=True, verbose_name='آیا نمایش داده شود؟')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ['-status', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='آدرس آیپی')),
                ('last_excessive_request_time', models.DateTimeField(verbose_name='آخرین وقت درخواست غیر مجاز')),
                ('excessive_requests_count', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='تعداد درخواست های بیش از حد اندازه')),
            ],
            options={
                'verbose_name': 'آیپی',
                'verbose_name_plural': 'آیپی ها',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان عکس')),
                ('slug', models.CharField(blank=True, max_length=250, unique=True, verbose_name='آدرس عکس')),
                ('img', models.ImageField(upload_to=app.models.upload_location, verbose_name='عکس شما')),
                ('original_size_image', models.CharField(blank=True, max_length=50, null=True, verbose_name='سایز پیش فرض عکس')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='app.category', verbose_name='دسته بندی')),
                ('download_count', models.ManyToManyField(blank=True, related_name='downloads', to=settings.AUTH_USER_MODEL, verbose_name='تعداد دانلود ها')),
                ('hits', models.ManyToManyField(blank=True, related_name='hits', to='app.Ip', verbose_name='بازدید ها')),
                ('likes_count', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='تعداد پسند ها')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='منتشر کننده')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست ها',
                'ordering': ['-created'],
            },
        ),
    ]
