POST_LIST_PAGE_SIZE = 30
DASHBOARD_POST_LIST_PAGE_SIZE = 15

VALID_IMAGE_FORMATS = ["JPEG", "PNG"]
MAX_IMAGE_UPLOAD_COUNT = 5 # In per day

MIN_BLOCK_TIME_EXCESSIVE_REQUESTS = 600 # Seconds
MAX_BLOCK_TIME_EXCESSIVE_REQUESTS = 900 # Seconds
MINIMUM_DIFFERENCE_REQUESTS = 1.0 # second float
MAX_COUNT_EXCESSIVE_REQUESTS = 5

MAIN_CATEGORIES_NUMBER = 5
USER_LAST_POSTS_COUNT = 6
SIDEBAR_ITEMS_COUNT = 6

SHOW_IMAGE_WIDTH = 1000
SHOW_IMAGE_HEIGHT = 1000
MIN_IMAGE_WIDTH = 300
MIN_IMAGE_HEIGHT = 300

RECENT_DAYS_STATISTICS_POSTS_NUMBER = 15
STATISTICS_POSTS_REVERSE = False

SIDEBAR_TAG_TITLES = {
    "suggestion": "عکس های پیشنهادی برای شما",
    "popular": "محبوب ترین عکس ها",
    "download": "پر دانلود ترین عکس ها",
    "hit": "پر بازدید ترین عکس ها",
}
